### ISSUE TITLE
Workflow Update causing WFT Failure with `Premature end of stream`

### ISSUE THREAD

**Issue by gauravthadani** [temporalio/temporal#7741]
## Expected Behavior
Expect no Workflow Task failure.

## Actual Behavior
- There is WF Task failure
- We know this is a transient and benign error, subsequent WFT fetches entire history and resumes well
- Monitoring on Workflow Task Failures causing alerts at Workers

## Steps to Reproduce the Problem

  1. Updates sent to Worfklows in cache after some time (approx. 3 hours)
  1.
  1.

## Specifications

  - Version: latest 1.27.2
  - Platform:

**Comment by yycptt** [comment]
Hi @gauravthadani Thanks for reporting!

Yes, we are aware of this issue and currently working on it. There will be a PR for this soon.
cc @alexshtin @stephanos

**Comment by stephanos** [comment]
Note that [the fix was merged](https://github.com/temporalio/temporal/pull/7732) but [subsequently reverted again](https://github.com/temporalio/temporal/pull/7878). Taking another stab at this soon.

**Comment by sethlurietfg** [comment]
Hey there. We are still getting this problem. Any chance of trying to get this fixed again?
